### ISSUE TITLE
Overall Score: 14.5/16

### ISSUE THREAD

**Issue by josephgupkim** [orenopt/jammming#5]
* _Score Level:_ 14.5/16
* _Comment(s):_ 

Your code base is clean and well organized but unfortunately because of the compiling error, I wasn't able to fully test the functionality aspect of your project. I don't doubt that it works flawlessly though based on the quality of your code. Other than that, awesome work on this Jammming project!

**Comment by josephgupkim** [comment]
<img width="762" alt="screen shot 2019-03-01 at 11 16 33 pm" src="https://user-images.githubusercontent.com/17152779/53678909-40a8ed00-3c7a-11e9-8916-a3541eaffe3b.png">

**Comment by orenopt** [comment]
Hi @josephgupkim,
I would like to kindly thank you for your professional review and remarks I will appreciate if
you can assist me further with figuring out the reason for the build failure as I am able to 
clone and rebuild fine on my end see my output below, I appreciate your comments.

:pray:
_**Thank you 
Oren**_

`
**_Oren@Oren-PC MINGW64 ~/Desktop/projects
$_** git clone https://github.com/orenopt/jammming.git
Cloning into 'jammming'...
remote: Enumerating objects: 103, done.
remote: Counting objects: 100% (103/103), done.
remote: Compressing objects: 100% (75/75), done.
remote: Total 1Re03 (dceelta 24), ivingre obusejd 102ect (delst:a 2 3), pa c7k-7                                 % re(80us/103), 3.ed29 MiB | 1 0
Receiving objects: 100% (103/103), 3.45 MiB | 1.12 MiB/s, done.
Resolving deltas: 100% (24/24), done.
Checking connectivity... done.

**_Oren@Oren-PC MINGW64 ~/Desktop/projects
$_** cd jammming

_**Oren@Oren-PC MINGW64 ~/Desktop/projects/jammming (master)
$**_ npm install
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 1811 packages from 716 contributors and audited 36220 packages in 65.845s
found 63 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details

**_Oren@Oren-PC MINGW64 ~/Desktop/projects/jammming (master)
$_** npm run build

> jammming@0.1.0 build C:\Users\Oren\Desktop\projects\jammming
> react-scripts build

Creating an optimized production build...
Compiled with warnings.

./src/Components/Track/Track.js
  Line 15:  The href attribute is required for an anchor to be keyboard accessible. Provide a valid, navigable address as the href value. If you cannot provide an href, but still need the element to resemble a link, use a button and change it with appropriate styles. Learn more: https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/anchor-is-valid.md  jsx-a11y/anchor-is-valid

./src/Components/Playlist/Playlist.js
  Line 21:  The href attribute is required for an anchor to be keyboard accessible. Provide a valid, navigable address as the href value. If you cannot provide an href, but still need the element to resemble a link, use a button and change it with appropriate styles. Learn more: https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/anchor-is-valid.md  jsx-a11y/anchor-is-valid

./src/Components/SearchBar/SearchBar.js
  Line 32:  The href attribute is required for an anchor to be keyboard accessible. Provide a valid, navigable address as the href value. If you cannot provide an href, but still need the element to resemble a link, use a button and change it with appropriate styles. Learn more: https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/anchor-is-valid.md  jsx-a11y/anchor-is-valid

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.

File sizes after gzip:

  37.01 KB  build\static\js\2.71b5da24.chunk.js
  1.8 KB    build\static\js\main.6ee8c38c.chunk.js
  897 B     build\static\css\main.80937663.chunk.css
  761 B     build\static\js\runtime~main.fdfcfda2.js

The project was built assuming it is hosted at the server root.
You can control this with the homepage field in your package.json.
For example, add this to build it for GitHub Pages:

  "homepage" : "http://myname.github.io/myapp",

The build folder is ready to be deployed.
You may serve it with a static server:

  serve -s build

Find out more about deployment here:

  http://bit.ly/CRA-deploy


**_Oren@Oren-PC MINGW64 ~/Desktop/projects/jammming (master)
$_** serve -s build
UPDATE AVAILABLE The latest version of `serve` is 10.1.2
INFO: Accepting connections at http://localhost:5000
`
