### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by tbergen1** [orenopt/jammming#6]
### Criteria 1: Objective
* **Score Level**: 4/4 (Exceeds Expectations)
* *Comment(s)*:  Your objective is a great one.  Being able to search with a filter is an awesome UX feature and will really make it easier for users to find what they are looking for.  Nice job!

### Criteria 2: Background
* **Score Level**: 4/4 (Exceeds Expectations)
* *Comment(s)*: Your background section is great!  It provides a detailed explanation of the pain point this feature is addressing.  You also gave a good summary of the overall functionality of the feature within the app.  Really awesome work!

### Criteria 3: Technical Design
* **Score Level**: 4/4 (Exceeds Expectations)
* *Comment(s)*: You did an good job on your technical design section.  It shows you put thought into how you would incorporate this feature and leverage existing functionality such as the Spotify search function to accomplish it.  Nice job!

### Criteria 4: Caveats
* **Score Level**: 1/4 (Does Not Meet Expectations)
* *Comment(s)*: While caveats might be hard to find, the intention of this section is to try and think about things that could possibly be done differently and why this may be the case.  It is an exercise in thought about the feature you are proposing.  You didn't propose any caveats and didn't really explain any train of thought that showed you attempted to do so.  It would have been good to put some sort of explanation about things you tried to think about.  Even something like a potential UI change and how that could affect the user.

### Overall Score: 13/16
Overall, you did an good job with this feature request.  You chose a feature that would greatly improve the UX of the app and explained the necessity for this feature clearly and concisely.  You also did well in detailing the specific aspects of the technical implementation.  It would have been good to get some caveats down or at least explain why there were none you could think of.  Good job!

**Comment by orenopt** [comment]
@tbergen1 thank you I appreciate your review and I will consider the remarks for future technical documentation assignments
